### ISSUE TITLE
Missing files for new users

### ISSUE THREAD

**Issue by diegoenry** [SuAVE-Software/source_v2.0#1]
Denys, 
apparently it’s not straightforward for a new users to run SuAVE. 
Therefore, it could benefit from:

1. A README file with a sort description2. 
2. A manual file, with a list of input parameters for each program. I would do it in .rst format and use “read the docs” to build documentation for you.
4. Compilation instructions (a Make file would be great)
5. A folder with example files
6. A link to publication

**Comment by SuAVE-Software** [comment]
Diego,

I would like to thank you for the comment. Fortunately, this is available on the official Suave website (https://www.biomatsite.net/suave-software). This GitHub page is still being developed and I hope to cover all points as soon as possible.

Please have a look at the website. You will see a Tutorial, Readme file explaining how to use and how to compile the code.

As to the publication, please see:

Santos, D. E. S.; Coutinho, K.; Soares, T. A. (2022) Surface Assessment Grid Evaluation (SuAVE) for Every Surface Curvature and Cavity Shape. Journal of Chemical Information and Modeling.

Santos, D. E. S.; Pontes, J. F. S.; Lins, R. D.; Coutinho, K.; Soares, T. A. (2020) SuAVE: A Tool for Analyzing Curvature-Dependent Properties in Chemical Interfaces. Journal of Chemical Information and Modeling, v. 60(2), p. 473-484.

**Comment by diegoenry** [comment]
Right on ! I’ll stay tuned for the documentation updates.
